backend/controllers/CustomerPformController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\CustomerPform;
use backend\models\CustomerPformSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * CustomerPformController implements the CRUD actions for CustomerPform model.
 */
class CustomerPformController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }



    /**
     * Lists all CustomerPform models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CustomerPformSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionStatistics()
    {
        $searchModel = new CustomerPformSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('statistics', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionExportstats()
    {
        $data = CustomerPform::statistic();
        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',
            'sheets' => [
                'Statistics' => [
                    'titles' => $data['title'],
                    'data' => $data['data'],
                ],
            ]
        ]);

        $file->send('statistics.xlsx');
    }
    /**
     * Displays a single CustomerPform model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CustomerPform model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'myform';
        $model = new CustomerPform();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing CustomerPform model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing CustomerPform model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CustomerPform model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CustomerPform the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CustomerPform::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/PformController.php
<?php

namespace backend\controllers;

use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

use backend\models\Pform;
use backend\models\PformSearch;

use backend\models\PformField;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use  yii\web\UploadedFile;

/**
 * PformController implements the CRUD actions for Pform model.
 */
class PformController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST', 'GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pform models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PformSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionStatistics()
    {
        $searchModel = new PformSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('statistics', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pform model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pform model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pform();

        if ($model->load(Yii::$app->request->post()) ) 
        {
             //上传列表小图片， 单文件上传
            $model->file = UploadedFile::getInstance($model, 'file');
            if(!empty($model->file))
            {
                $targetFileId = date("YmdHis").'-'.uniqid();
                $ext = pathinfo($model->file->name, PATHINFO_EXTENSION);
                $targetFileName = "{$targetFileId}.{$ext}";
                $targetFile = Yii::getAlias('@webroot') . DIRECTORY_SEPARATOR . "uploads" . DIRECTORY_SEPARATOR . $targetFileName;

                $targetFileUrl = Yii::getAlias('@web') . "/" . "uploads" . "/" . $targetFileName;

                $model->file->saveAs($targetFile);

                $model->form_img_url = $targetFileUrl;
            }

            $model->user_id = Yii::$app->user->id;
            $model->uid = uniqid();
            $model->save(false);

            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pform model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) ) {

            //上传列表小图片， 单文件上传
            $model->file = UploadedFile::getInstance($model, 'file');
            if(!empty($model->file))
            {
                $targetFileId = date("YmdHis").'-'.uniqid();
                $ext = pathinfo($model->file->name, PATHINFO_EXTENSION);
                $targetFileName = "{$targetFileId}.{$ext}";
                $targetFile = Yii::getAlias('@webroot') . DIRECTORY_SEPARATOR . "uploads" . DIRECTORY_SEPARATOR . $targetFileName;

                $targetFileUrl = Yii::getAlias('@web') . "/" . "uploads" . "/" . $targetFileName;

                $model->file->saveAs($targetFile);

                $model->form_img_url = $targetFileUrl;
            }

            $model->save(false);

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pform model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    

    public function actionDelformfield($view_id, $formfield_id)
    {
        //$this->findModel($id)->delete();
        PformField::findOne(['id' => $formfield_id])->delete();

        return $this->redirect(['view', 'id' => $view_id]);
    }


    /**
     * Finds the Pform model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pform the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pform::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'ajax-broker'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

      
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAjaxBroker($args) {
        $args = json_decode($args, true);
        return call_user_func_array(array($args['classname'], $args['funcname']), $args['params']);
    }
}

backend/views/pform/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\PformSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pform-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'uid') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pform/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PformSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '表单';
$this->params['breadcrumbs'][] = $this->title;
?>
<style type="text/css">
    .filters {
        display: none;
    }

</style>

<div class="pform-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('创建表单', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions' =>['class' => 'table table-striped'],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'id',
                'headerOptions' => array('style'=>'width:8%;'),
            ], 
            //'form_img_url',

            [
                'attribute' => 'form_img_url',
                'format' => 'raw',
                'value' => function($model, $key, $index, $column){
                    if(!empty($model->form_img_url))
                        $form_img_url = '<img src=' . $model->form_img_url .' width=160px height=90px>';
                    else
                        $form_img_url = '<img src=http://iph.href.lu/160x90?text=preview>';

                    $form_link = Yii::$app->request->hostInfo ."/customer-pform/create?pform_uid=".$model->uid;
                    $form_title = $model->title;

                    $preview_btn = "<button class='btn btn-default btn-form-link' style='width:160px' data-toggle='modal' data-target='#myModal1' form_title_attr='".$form_title."' form_link_attr='".$form_link."'><i class='glyphicon glyphicon-phone'></i> 预览表单</button>";

                    return $form_img_url . "<br>" . $preview_btn;
                },
                'headerOptions' => array('style'=>'width:160px;'),
            ],

            //'uid',
            //'title',
            [
                'attribute' => 'title',
                'format' => 'html',
                'value' => function($model, $key, $index, $column){

                    $form_link = Yii::$app->request->hostInfo ."/customer-pform/create?pform_uid=".$model->uid;
                    return $model->title . "<br><br>填表链接(可直接复制以下链接到网站、微信中使用)：<br>" . $form_link;
                },
                'headerOptions' => array('style'=>'width:300px;'),
            ],

     
           //'description',

            // [
            //     'attribute' => 'detail',
            //     'format' => 'html',
            // ],

            // [
            //     'label' => '表单预览',
            //     'format' => 'raw',
            //     'value'=>function ($model, $key, $index, $column) {
            //         //$url = "/customer-pform/create?pform_uid=".$model->uid;

            //         //return Html::a('预览', ['customer-pform/create', 'pform_uid' =>$model->uid]);
            //         //http://pf.beesoft.com/customer-pform/create?pform_uid=594e763b8a4a4
            //         //链接到前端视图， 暂时硬编码。

            //         //return "<a href=". Yii::$app->request->hostInfo ."/customer-pform/create?pform_uid=".$model->uid.">预览</a>";

            //         $form_link = Yii::$app->request->hostInfo ."/customer-pform/create?pform_uid=".$model->uid;
            //         $form_title = $model->title;

            //         return "<button class='btn btn-default btn-form-link' data-toggle='modal' data-target='#myModal1' form_title_attr='".$form_title."' form_link_attr='".$form_link."'><i class='glyphicon glyphicon-phone'></i> 预览</button>";
            //     },

            //     //'headerOptions' => array('style'=>'width:70px;'),
            // ],

            [
                'label' => '包含字段',
                'value'=>function ($model, $key, $index, $column) {

                    $formfields = \backend\models\PformField::find()
                                    ->where(["pform_uid" => $model->uid])
                                    ->all();

                    $field_str = "";
                    if(empty($formfields))
                        return $field_str;

                    foreach ($formfields as $formfield) {
                        $field_str = $field_str."【".$formfield->title."】<br>";
                    }
                    return "<span>".$field_str."</span>";
                },
                'format' => 'html',
                //'filter' => \common\models\CampaignOrder::getGhOption(),
                'headerOptions' => array('style'=>'width:25%;'),
            ],

            // 'created_at:datetime',
            // 'updated_at:datetime',
            // 'user_id',
            // 'description',
            //http://127.0.0.1/adv/backend/web/index.php?PformFieldSearch%5Bpform_uid%5D=594cd9feac29c&r=pform-field
            
            [
                'label' => '填表数',
                'format' => 'html',
                'value' => function ($model, $key, $index, $column) {                        
                    $customerform_count = \backend\models\CustomerPform::find()
                        ->select(['customer_pform_uid'])
                        ->where(["pform_uid" => $model->uid])
                        ->distinct()
                        ->count();
                    return $customerform_count;
                },
                'headerOptions' => array('style'=>'width:14%;'),
            ],

            [
                'class' => 'yii\grid\ActionColumn', 
                 // 'label' => '填表数据',
                //'template' => '{addbackcover} {view} {update} {delete} {list}',
                'template' => '{myview} {addbackcover} {update} {list} {delete}',
                'headerOptions' => array('style'=>'width:12%;'),
                'buttons' => [
                    'myview' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-plus" style="color:#5CB85C; margin-left:8px; font-size:28px">', ['pform/view', 'id' => $model->id], ['title' => '添加表单字段']);
                    },

                    'list' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-stats" style="color:#F0AD4E; margin-left:8px; font-size:28px"></span>', ['customer-pform/statistics', 'uid' => $model->uid], ['title' => '查看填表数据']);
                    },

                    'update' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-pencil" style="color:#C9302C; margin-left:8px; font-size:28px"></span>', ['pform/update', 'id' => $model->id], ['title' => '修改']);
                    },

                    'addbackcover' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-file" style="color:#337AB7; margin-left:8px; font-size:28px"></span>', ['pform-backcover/add', 'uid' => $model->uid], ['title' => '增加填表成功页面']);
                    },

                    'delete' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-trash" style="color:red; margin-left:8px; font-size:28px"></span>', ['pform/delete', 'id' => $model->id], ['title' => '删除表单']);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

<!-- 二维码模式窗口 for mobile -->
<div class="modal fade"  id="myModal1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">预览表单</h3>
            </div>
            <div class="modal-body">
                <h4 class="modal-title" id="form_title"></h4>

                <div class="alert alert-success" role="alert" id="preview"</div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-success" id="addMetadata">确定</button>
            </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function(){
        var host = "<?= Yii::$app->request->hostInfo ?>";
       
        $(".btn-form-link").click(function(){

            var form_link_attr = $(this).attr("form_link_attr");
            var form_title = $(this).attr("form_title_attr");
            
            var preview = "<img width=100% src='http://qr.liantu.com/api.php?text=" + form_link_attr +  "' /> <small class='center-block text-center'>手机扫一扫预览</small>";
            var preview1 = "<a href='" + host + "/customer-pform/preview?text=" + form_link_attr +  "'>PC上预览</a>";

            $("#preview").html(preview);
       
            $("#form_title").html(form_title + '&nbsp;&nbsp; <small>' + preview1 + '</small>');
        });

    });//end of documnet ready

</script>

backend/views/pform/statistics.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = '表单统计';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pform-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'headerOptions' => array('style'=>'width:8%;'),
            ], [
                'attribute' => 'form_img_url',
                'format' => 'html',
                'value' => function($model, $key, $index, $column){
                    if(!empty($model->form_img_url))
                        $form_img_url = '<img src=/admin' . $model->form_img_url .' width=160px height=90px>';
                    else
                        $form_img_url = '';

                    return $form_img_url;
                },
                'headerOptions' => array('style'=>'width:160px;'),
            ], 'title', [
                'label' => '填单人数',
                'format' => 'html',
                'value' => function ($model, $key, $index, $column) {
                    // $customerform_count = \backend\models\CustomerPform::find()
                    //     ->where(["pform_uid" => $model->uid])
                    //     ->count();
                    // $formfield_count = \backend\models\PformField::find()
                    //     ->where(["pform_uid" => $model->uid])
                    //     ->count();
                    // return $customerform_count/$formfield_count;
                    
                    $customerform_count = \backend\models\CustomerPform::find()
                        ->select(['customer_pform_uid'])
                        ->where(["pform_uid" => $model->uid])
                        ->distinct()
                        ->count();
                    return $customerform_count;
                },
            ], [
                'label' => '包含字段',
                'value'=>function ($model, $key, $index, $column) {

                    $formfields = \backend\models\PformField::find()
                                    ->where(["pform_uid" => $model->uid])
                                    ->all();

                    $field_str = "";
                    if(empty($formfields))
                        return $field_str;

                    foreach ($formfields as $formfield) {
                        $field_str = $field_str."【".$formfield->title."】<br>";
                    }
                    return "<span style='color:blue; font-size:12pt'>".$field_str."</span>";
                },
                'format' => 'html',
                //'filter' => \common\models\CampaignOrder::getGhOption(),
                'headerOptions' => array('style'=>'width:25%;'),
            ], [
                'class' => 'yii\grid\ActionColumn', 
                'template' => '{list}',
                'headerOptions' => array('style'=>'width:12%;'),
                'buttons' => [
                    'list' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['customer-pform/statistics', 'uid' => $model->uid]);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/pform/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\Pform */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => '表单', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
    
</style>

<script>
    var ajaxUrl = "<?= Url::to(['/site/ajax-broker']); ?>";
</script>

<div class="pform-view">

    <h1>
        <?= Html::encode($this->title) ?>
        &nbsp;&nbsp;
        <button class="btn btn-success" data-toggle="modal" data-target="#myModal">新增字段 <i class="glyphicon glyphicon-plus"></i></button>
    </h1>

    <!--
    <p>
        <//?= Html::a('修改', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <//?= Html::a('删除', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '删除表单，确定?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    -->

    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'table table-striped detail-view'],
        'attributes' => [
            'id',
            'uid',
            'title',
            'description',
            [
               'attribute' => 'detail',
               'format'=> 'html',
            ],

            [
                'label' => '包含字段',
                'value' => $model->getFormField($model),
                'format'=> 'html',
            ],

            'created_at:datetime',
            'updated_at:datetime',
            //'user_id',
        ],
    ]) ?>


</div>



<!-- Modal -->
<div class="modal fade"  id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">新增字段</h3>
            </div>

            
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group field-product-title">
                            <h3><P><?= $model->title ?> </P></h3>
                            <p><?= $model->description ?></p>
                        </div>
                    </div>
                </div>

                <hr>
                <input type="hidden" id="form_uid" value="<?= $model->uid ?>">
                <div class="form-group">
                    <label class="control-label" for="field_title">字段名称</label>
                    <input type="text" id="field_title" class="form-control" name="field_title" maxlength="32" placeholder="填写字段名称，如 名字，手机号码 ...">
                    <div class="help-block"></div>
                </div>
              
                <div class="form-group">
                    <label class="control-label" for="field_type">字段类型</label>
                    <select class="form-control" id="field_type" name="field_type">
                    <option value="1">普通文本</option>
                    <option value="2">电话号码</option>
                    <option value="3">电子邮箱</option>
                    <option value="4">单项选择</option>
                    <option value="5">多项选择</option>
                    <option value="6">备注</option>
                    </select>
                    <div class="help-block"></div>
                </div>

                <div class="form-group field_value">
                    <label class="control-label" for="field_value">字段取值范围</label>
                    <input type="text" id="field_value" class="form-control" name="field_value" maxlength="255" placeholder="选项内容用空格分开，如喜欢的水果：西瓜 苹果 葡萄">
                    <div class="help-block"></div>
                </div>

                <div class="form-group">
                    <label class="control-label" for="field_placeholder">字段提示语</label>
                    <input type="text" id="field_placeholder" class="form-control" name="field_placeholder" maxlength="255">
                    <div class="help-block"></div>
                </div>

                <div class="form-group hide">
                    <label class="control-label" for="field_order">排序</label>
                    <input type="text" id="field_order" class="form-control" name="field_order" maxlength="32">
                    <div class="help-block"></div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-success" id="addMetadata">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<script type="text/javascript">
    $('.field_value').hide();

    var form_uid;
    var field_title;
    var field_type;
    var field_value;
    var field_placeholder;
    var field_order;


    function addMetadataAjax() {
        var args = {
            'classname': '\\backend\\models\\Pform',
            'funcname': 'addMetadataAjax',
            'params': {
                'form_uid': form_uid,
                'field_title': field_title,
                'field_type': field_type,
                'field_value': field_value,
                'field_placeholder': field_placeholder,
                'field_order': field_order,
            }
        };
        $.ajax({
            url: ajaxUrl,
            type: 'GET',
            cache: false,
            dataType: 'json',
            data: 'args=' + JSON.stringify(args),
            success: function (ret) {
                location.reload();
            },
            error: function () {
            }
        });
    }

    $('#addMetadata').click (function () {
        form_uid = $('#form_uid').val();
        field_title = $('#field_title').val();
        field_type = $('#field_type').val();
        field_value = $('#field_value').val();
        field_placeholder = $('#field_placeholder').val();
        field_order = $('#field_order').val();

        //alert(form_uid+"--"+field_title+"--"+field_type+"--"+field_value+"--"+field_placeholder+"--"+field_order);

        addMetadataAjax();
    });


    $('#field_type').change (function () {
        if($('#field_type').val() > 3)
            $('.field_value').show();
        else
            $('.field_value').hide();
    });


</script>